// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        int64     `gorm:"column:uid;not null" json:"uid"` // 用户ID
	Cid        int64     `gorm:"column:cid;not null" json:"cid"` // 类别ID
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	Title      string    `gorm:"column:title;not null" json:"title"`
	Content    string    `gorm:"column:content;not null" json:"content"`
	HeadImage  string    `gorm:"column:head_image" json:"head_image"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
