// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	Name       string    `gorm:"column:name;not null" json:"name"`         // 用户姓名
	Mobile     string    `gorm:"column:mobile;not null" json:"mobile"`     // 用户电话
	Password   string    `gorm:"column:password;not null" json:"password"` // 用户密码
	Collects   string    `gorm:"column:collects" json:"collects"`
	Following  string    `gorm:"column:following" json:"following"`
	Fans       int32     `gorm:"column:fans;not null" json:"fans"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
